import namespace, { NamespaceBuilder } from "@rdfjs/namespace";
import { NamedNode } from "@rdfjs/types";

interface Geo {
    '': NamedNode<'http://www.opengis.net/ont/geosparql#'>;
    "Feature": NamedNode<'http://www.opengis.net/ont/geosparql#Feature'>;
    "SpatialObject": NamedNode<'http://www.opengis.net/ont/geosparql#SpatialObject'>;
    "Geometry": NamedNode<'http://www.opengis.net/ont/geosparql#Geometry'>;
    "FeatureCollection": NamedNode<'http://www.opengis.net/ont/geosparql#FeatureCollection'>;
    "SpatialObjectCollection": NamedNode<'http://www.opengis.net/ont/geosparql#SpatialObjectCollection'>;
    "GeometryCollection": NamedNode<'http://www.opengis.net/ont/geosparql#GeometryCollection'>;
    "asDGGS": NamedNode<'http://www.opengis.net/ont/geosparql#asDGGS'>;
    "dggsLiteral": NamedNode<'http://www.opengis.net/ont/geosparql#dggsLiteral'>;
    "hasSerialization": NamedNode<'http://www.opengis.net/ont/geosparql#hasSerialization'>;
    "asGML": NamedNode<'http://www.opengis.net/ont/geosparql#asGML'>;
    "gmlLiteral": NamedNode<'http://www.opengis.net/ont/geosparql#gmlLiteral'>;
    "asGeoJSON": NamedNode<'http://www.opengis.net/ont/geosparql#asGeoJSON'>;
    "geoJSONLiteral": NamedNode<'http://www.opengis.net/ont/geosparql#geoJSONLiteral'>;
    "asKML": NamedNode<'http://www.opengis.net/ont/geosparql#asKML'>;
    "kmlLiteral": NamedNode<'http://www.opengis.net/ont/geosparql#kmlLiteral'>;
    "asWKT": NamedNode<'http://www.opengis.net/ont/geosparql#asWKT'>;
    "wktLiteral": NamedNode<'http://www.opengis.net/ont/geosparql#wktLiteral'>;
    "coordinateDimension": NamedNode<'http://www.opengis.net/ont/geosparql#coordinateDimension'>;
    "defaultGeometry": NamedNode<'http://www.opengis.net/ont/geosparql#defaultGeometry'>;
    "hasGeometry": NamedNode<'http://www.opengis.net/ont/geosparql#hasGeometry'>;
    "hasDefaultGeometry": NamedNode<'http://www.opengis.net/ont/geosparql#hasDefaultGeometry'>;
    "dimension": NamedNode<'http://www.opengis.net/ont/geosparql#dimension'>;
    "ehContains": NamedNode<'http://www.opengis.net/ont/geosparql#ehContains'>;
    "ehCoveredBy": NamedNode<'http://www.opengis.net/ont/geosparql#ehCoveredBy'>;
    "ehCovers": NamedNode<'http://www.opengis.net/ont/geosparql#ehCovers'>;
    "ehDisjoint": NamedNode<'http://www.opengis.net/ont/geosparql#ehDisjoint'>;
    "sfDisjoint": NamedNode<'http://www.opengis.net/ont/geosparql#sfDisjoint'>;
    "ehEquals": NamedNode<'http://www.opengis.net/ont/geosparql#ehEquals'>;
    "sfEquals": NamedNode<'http://www.opengis.net/ont/geosparql#sfEquals'>;
    "ehInside": NamedNode<'http://www.opengis.net/ont/geosparql#ehInside'>;
    "ehMeet": NamedNode<'http://www.opengis.net/ont/geosparql#ehMeet'>;
    "sfTouches": NamedNode<'http://www.opengis.net/ont/geosparql#sfTouches'>;
    "ehOverlap": NamedNode<'http://www.opengis.net/ont/geosparql#ehOverlap'>;
    "hasArea": NamedNode<'http://www.opengis.net/ont/geosparql#hasArea'>;
    "hasSize": NamedNode<'http://www.opengis.net/ont/geosparql#hasSize'>;
    "hasBoundingBox": NamedNode<'http://www.opengis.net/ont/geosparql#hasBoundingBox'>;
    "hasCentroid": NamedNode<'http://www.opengis.net/ont/geosparql#hasCentroid'>;
    "hasLength": NamedNode<'http://www.opengis.net/ont/geosparql#hasLength'>;
    "hasMetricArea": NamedNode<'http://www.opengis.net/ont/geosparql#hasMetricArea'>;
    "hasMetricSize": NamedNode<'http://www.opengis.net/ont/geosparql#hasMetricSize'>;
    "hasMetricLength": NamedNode<'http://www.opengis.net/ont/geosparql#hasMetricLength'>;
    "hasMetricPerimeterLength": NamedNode<'http://www.opengis.net/ont/geosparql#hasMetricPerimeterLength'>;
    "hasMetricSpatialAccuracy": NamedNode<'http://www.opengis.net/ont/geosparql#hasMetricSpatialAccuracy'>;
    "hasMetricSpatialResolution": NamedNode<'http://www.opengis.net/ont/geosparql#hasMetricSpatialResolution'>;
    "hasMetricVolume": NamedNode<'http://www.opengis.net/ont/geosparql#hasMetricVolume'>;
    "hasPerimeterLength": NamedNode<'http://www.opengis.net/ont/geosparql#hasPerimeterLength'>;
    "hasSpatialAccuracy": NamedNode<'http://www.opengis.net/ont/geosparql#hasSpatialAccuracy'>;
    "hasSpatialResolution": NamedNode<'http://www.opengis.net/ont/geosparql#hasSpatialResolution'>;
    "hasVolume": NamedNode<'http://www.opengis.net/ont/geosparql#hasVolume'>;
    "isEmpty": NamedNode<'http://www.opengis.net/ont/geosparql#isEmpty'>;
    "isSimple": NamedNode<'http://www.opengis.net/ont/geosparql#isSimple'>;
    "rcc8dc": NamedNode<'http://www.opengis.net/ont/geosparql#rcc8dc'>;
    "rcc8ec": NamedNode<'http://www.opengis.net/ont/geosparql#rcc8ec'>;
    "rcc8eq": NamedNode<'http://www.opengis.net/ont/geosparql#rcc8eq'>;
    "rcc8ntpp": NamedNode<'http://www.opengis.net/ont/geosparql#rcc8ntpp'>;
    "rcc8ntppi": NamedNode<'http://www.opengis.net/ont/geosparql#rcc8ntppi'>;
    "rcc8po": NamedNode<'http://www.opengis.net/ont/geosparql#rcc8po'>;
    "rcc8tpp": NamedNode<'http://www.opengis.net/ont/geosparql#rcc8tpp'>;
    "rcc8tppi": NamedNode<'http://www.opengis.net/ont/geosparql#rcc8tppi'>;
    "sfContains": NamedNode<'http://www.opengis.net/ont/geosparql#sfContains'>;
    "sfCrosses": NamedNode<'http://www.opengis.net/ont/geosparql#sfCrosses'>;
    "sfIntersects": NamedNode<'http://www.opengis.net/ont/geosparql#sfIntersects'>;
    "sfOverlaps": NamedNode<'http://www.opengis.net/ont/geosparql#sfOverlaps'>;
    "sfWithin": NamedNode<'http://www.opengis.net/ont/geosparql#sfWithin'>;
    "spatialDimension": NamedNode<'http://www.opengis.net/ont/geosparql#spatialDimension'>;
}

const builder = namespace("http://www.opengis.net/ont/geosparql#") as any;
export const strict = builder as NamespaceBuilder<keyof Geo> & Geo;
export const loose = builder as NamespaceBuilder & Geo;
