import { prefixes } from "@zazuko/rdf-vocabularies";
import namespace, { NamespaceBuilder } from "@rdfjs/namespace";
import { NamedNode } from "rdf-js";
type Geof = NamespaceBuilder & {
    "boundary": NamedNode;
    "buffer": NamedNode;
    "convexHull": NamedNode;
    "difference": NamedNode;
    "distance": NamedNode;
    "ehContains": NamedNode;
    "ehCoveredBy": NamedNode;
    "ehCovers": NamedNode;
    "ehDisjoint": NamedNode;
    "ehEquals": NamedNode;
    "ehInside": NamedNode;
    "ehMeet": NamedNode;
    "ehOverlap": NamedNode;
    "envelope": NamedNode;
    "getSRID": NamedNode;
    "intersection": NamedNode;
    "rcc8dc": NamedNode;
    "rcc8ec": NamedNode;
    "rcc8eq": NamedNode;
    "rcc8ntpp": NamedNode;
    "rcc8ntppi": NamedNode;
    "rcc8po": NamedNode;
    "rcc8tpp": NamedNode;
    "rcc8tppi": NamedNode;
    "relate": NamedNode;
    "sfContains": NamedNode;
    "sfCrosses": NamedNode;
    "sfDisjoint": NamedNode;
    "sfEquals": NamedNode;
    "sfIntersects": NamedNode;
    "sfOverlaps": NamedNode;
    "sfTouches": NamedNode;
    "sfWithin": NamedNode;
    "symDifference": NamedNode;
    "union": NamedNode;
};
export const geof: Geof = (namespace("http://www.opengis.net/def/function/geosparql/") as any);
