import namespace, { NamespaceBuilder } from "@rdf-esm/namespace";
import { NamedNode } from "rdf-js";
type Rdfa = NamespaceBuilder & {
    "DocumentError": NamedNode;
    "Error": NamedNode;
    "Info": NamedNode;
    "PGClass": NamedNode;
    "Pattern": NamedNode;
    "PrefixMapping": NamedNode;
    "PrefixOrTermMapping": NamedNode;
    "PrefixRedefinition": NamedNode;
    "TermMapping": NamedNode;
    "UnresolvedCURIE": NamedNode;
    "UnresolvedTerm": NamedNode;
    "VocabReferenceError": NamedNode;
    "Warning": NamedNode;
    "context": NamedNode;
    "copy": NamedNode;
    "prefix": NamedNode;
    "term": NamedNode;
    "uri": NamedNode;
    "usesVocabulary": NamedNode;
    "vocabulary": NamedNode;
};
export const rdfa: Rdfa = (namespace("http://www.w3.org/ns/rdfa#") as any);
