import namespace, { NamespaceBuilder } from "@rdf-esm/namespace";
import { NamedNode } from "rdf-js";

interface Vaem {
    "Aspect": NamedNode<'http://www.linkedmodel.org/schema/vaem#Aspect'>;
    "CatalogEntry": NamedNode<'http://www.linkedmodel.org/schema/vaem#CatalogEntry'>;
    "CollectionGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#CollectionGraph'>;
    "ConstraintsGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#ConstraintsGraph'>;
    "ControllersGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#ControllersGraph'>;
    "CurationGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#CurationGraph'>;
    "DataGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#DataGraph'>;
    "Dimension": NamedNode<'http://www.linkedmodel.org/schema/vaem#Dimension'>;
    "Discipline": NamedNode<'http://www.linkedmodel.org/schema/vaem#Discipline'>;
    "DocumentationGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#DocumentationGraph'>;
    "Domain": NamedNode<'http://www.linkedmodel.org/schema/vaem#Domain'>;
    "FunctionsGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#FunctionsGraph'>;
    "GMD_VAEM": NamedNode<'http://www.linkedmodel.org/schema/vaem#GMD_VAEM'>;
    "GraphMetaData": NamedNode<'http://www.linkedmodel.org/schema/vaem#GraphMetaData'>;
    "GraphRole": NamedNode<'http://www.linkedmodel.org/schema/vaem#GraphRole'>;
    "LinkSetGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#LinkSetGraph'>;
    "MappingGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#MappingGraph'>;
    "Party": NamedNode<'http://www.linkedmodel.org/schema/vaem#Party'>;
    "ProxyGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#ProxyGraph'>;
    "RulesGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#RulesGraph'>;
    "SchemaGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#SchemaGraph'>;
    "ScriptGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#ScriptGraph'>;
    "TopQuadrant": NamedNode<'http://www.linkedmodel.org/schema/vaem#TopQuadrant'>;
    "TransformsGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#TransformsGraph'>;
    "ViewGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#ViewGraph'>;
    "Viewpoint": NamedNode<'http://www.linkedmodel.org/schema/vaem#Viewpoint'>;
    "VocabularyGraph": NamedNode<'http://www.linkedmodel.org/schema/vaem#VocabularyGraph'>;
    "abbreviation": NamedNode<'http://www.linkedmodel.org/schema/vaem#abbreviation'>;
    "acronym": NamedNode<'http://www.linkedmodel.org/schema/vaem#acronym'>;
    "comment": NamedNode<'http://www.linkedmodel.org/schema/vaem#comment'>;
    "date": NamedNode<'http://www.linkedmodel.org/schema/vaem#date'>;
    "dateCreated": NamedNode<'http://www.linkedmodel.org/schema/vaem#dateCreated'>;
    "description": NamedNode<'http://www.linkedmodel.org/schema/vaem#description'>;
    "filePrefix": NamedNode<'http://www.linkedmodel.org/schema/vaem#filePrefix'>;
    "hasAspect": NamedNode<'http://www.linkedmodel.org/schema/vaem#hasAspect'>;
    "hasDimension": NamedNode<'http://www.linkedmodel.org/schema/vaem#hasDimension'>;
    "hasDiscipline": NamedNode<'http://www.linkedmodel.org/schema/vaem#hasDiscipline'>;
    "hasDomain": NamedNode<'http://www.linkedmodel.org/schema/vaem#hasDomain'>;
    "hasGraphMetadata": NamedNode<'http://www.linkedmodel.org/schema/vaem#hasGraphMetadata'>;
    "hasGraphRole": NamedNode<'http://www.linkedmodel.org/schema/vaem#hasGraphRole'>;
    "hasIdentifier": NamedNode<'http://www.linkedmodel.org/schema/vaem#hasIdentifier'>;
    "hasLicenseType": NamedNode<'http://www.linkedmodel.org/schema/vaem#hasLicenseType'>;
    "hasMetadata": NamedNode<'http://www.linkedmodel.org/schema/vaem#hasMetadata'>;
    "hasOwner": NamedNode<'http://www.linkedmodel.org/schema/vaem#hasOwner'>;
    "hasSteward": NamedNode<'http://www.linkedmodel.org/schema/vaem#hasSteward'>;
    "hasViewpoint": NamedNode<'http://www.linkedmodel.org/schema/vaem#hasViewpoint'>;
    "id": NamedNode<'http://www.linkedmodel.org/schema/vaem#id'>;
    "idString": NamedNode<'http://www.linkedmodel.org/schema/vaem#idString'>;
    "intent": NamedNode<'http://www.linkedmodel.org/schema/vaem#intent'>;
    "isElaboratedIn": NamedNode<'http://www.linkedmodel.org/schema/vaem#isElaboratedIn'>;
    "lastUpdated": NamedNode<'http://www.linkedmodel.org/schema/vaem#lastUpdated'>;
    "latestPublishedVersion": NamedNode<'http://www.linkedmodel.org/schema/vaem#latestPublishedVersion'>;
    "logo": NamedNode<'http://www.linkedmodel.org/schema/vaem#logo'>;
    "name": NamedNode<'http://www.linkedmodel.org/schema/vaem#name'>;
    "namespace": NamedNode<'http://www.linkedmodel.org/schema/vaem#namespace'>;
    "namespacePrefix": NamedNode<'http://www.linkedmodel.org/schema/vaem#namespacePrefix'>;
    "ownedBy": NamedNode<'http://www.linkedmodel.org/schema/vaem#ownedBy'>;
    "owner": NamedNode<'http://www.linkedmodel.org/schema/vaem#owner'>;
    "owningParty": NamedNode<'http://www.linkedmodel.org/schema/vaem#owningParty'>;
    "previousPublishedVersion": NamedNode<'http://www.linkedmodel.org/schema/vaem#previousPublishedVersion'>;
    "rationale": NamedNode<'http://www.linkedmodel.org/schema/vaem#rationale'>;
    "rdfxmlFileURL": NamedNode<'http://www.linkedmodel.org/schema/vaem#rdfxmlFileURL'>;
    "reifiableBy": NamedNode<'http://www.linkedmodel.org/schema/vaem#reifiableBy'>;
    "releaseDate": NamedNode<'http://www.linkedmodel.org/schema/vaem#releaseDate'>;
    "revision": NamedNode<'http://www.linkedmodel.org/schema/vaem#revision'>;
    "specificity": NamedNode<'http://www.linkedmodel.org/schema/vaem#specificity'>;
    "title": NamedNode<'http://www.linkedmodel.org/schema/vaem#title'>;
    "todo": NamedNode<'http://www.linkedmodel.org/schema/vaem#todo'>;
    "turtleFileURL": NamedNode<'http://www.linkedmodel.org/schema/vaem#turtleFileURL'>;
    "url": NamedNode<'http://www.linkedmodel.org/schema/vaem#url'>;
    "usesNonImportedResource": NamedNode<'http://www.linkedmodel.org/schema/vaem#usesNonImportedResource'>;
    "withAttributionTo": NamedNode<'http://www.linkedmodel.org/schema/vaem#withAttributionTo'>;
}

const builder = namespace("http://www.linkedmodel.org/schema/vaem#") as any;
export const strict = builder as NamespaceBuilder<keyof Vaem> & Vaem;
export const loose = builder as NamespaceBuilder & Vaem;
